# Promise基础

## 概念

**回调函数**：

当一个函数作为**参数**传入另一个参数中，并且它不会立即执行，只有当满足一定条件后该函数才可以执行

**同步任务**：

在主线程上排队执行，只有前一个任务执行完毕，才能执行下一个任务

**异步任务**：

异步任务不进入主线程，而是进入异步队列，前一个任务是否执行完毕不影响下一个任务的执行

## 异步编程

* fs 文件操作

  ```js
  require('fs').readFile('./index.html', (err,data)=>{})
  ```

* 数据库操作

* AJAX 

  ```js
    $.get('/server', (data)=>{})
  ```

* 定时器 

  ```js
  setTimeout(()=>{}, 2000);
  ```

## Promise 是什么

Promise 是一门新的技术(ES6 规范) 

Promise 是 JS 中进行**异步编程**的新解决方案 备注：旧方案是单纯使用回调函数 

具体表达: 

1) 从语法上来说: Promise 是一个构造函数 
2)  从功能上来说: promise 对象用来封装一个异步操作并可以获取其成功/ 失败的结果值 

## 为什么要用 Promise

**指定回调函数的方式更加灵活** 

1. 旧的: 必须在启动异步任务前指定 
2. promise: 启动异步任务 => 返回promie对象 => 给promise对象绑定回调函 数(甚至可以在异步任务结束后指定/多个) 

支持**链式调用**, 可以解决**回调地狱**问题 

- 回调地狱：回调函数**嵌套调用**, 外部回调函数异步执行的结果是嵌套的回调执行的条件 
- 回调地狱的缺点：不便于阅读 不便于异常处理
- 解决方案：promise 链式调用
- 终极解决方案
- async/await

## Promise 的状态

实例对象中的一个属性 『PromiseState』
* pending  未决定的
* resolved / fullfilled  成功
* rejected  失败

**状态改变**：只能有2种

- pending 变为 resolved 
- pending 变为 rejected 

一个 promise 对象只能改变一次 无论变为成功还是失败, 都会有一个结果数据 

- 成功的结果数据一般称为 value,
- 失败的结果数据一般称为 reason

## Promise 对象的值
实例对象中的另一个属性 『PromiseResult』
保存着异步任务『成功/失败』的结果

* resolve
* reject 

## Promise 工作流程

![](https://img-blog.csdnimg.cn/20210708174409944.png)

# Promise深入

## API

参考[代码](code\1-promise基础\7-Promise的API.html)

### Promise 构造函数

`Promise (excutor) {}`

 (1) executor 函数: 执行器 `(resolve, reject) => {} `

 (2) resolve 函数: 内部定义成功时我们调用的函数 `value => {} `

(3) reject 函数: 内部定义失败时我们调用的函数 `reason => {}` 

说明: executor 会在 Promise 内部立即同步调用,异步操作在执行器中执行 

### Promise.prototype.then 方法

`(onResolved, onRejected) => {}` 

(1) onResolved 函数: 成功的回调函数 `(value) => {} `

(2) onRejected 函数: 失败的回调函数 `(reason) => {} `

说明: 指定用于得到成功 value 的成功回调和用于得到失败 reason 的失败回调 返回一个新的 promise 对象 

### Promise.prototype.catch 方法

`(onRejected) => {}` 

(1) onRejected 函数: 失败的回调函数 `(reason) => {}`

说明: then()的语法糖, 相当于: then(undefined, onRejected)

### Promise.prototype.finally 方法

不管Promise对象处于什么状态，都会执行回调函数

回调函数不接收参数，意味着它根本不care

等效于p.finally()then()

### Promise.resolve 方法

`(value) => {} `

(1) value: 成功的数据或 promise 对象 

说明: 返回一个成功/失败的 promise 对象

### Promise.reject 方法

`(reason) => {} `

(1) reason: 失败的原因 

说明: 返回一个失败的 promise 对象

### Promise.all([p1,p2,p3]) 方法

`(promises) => {}` 

(1) promises: 包含 n 个 promise 的数组 

说明: 返回一个新的 promise, 

- 只有所有的 promise 都成功才成功,
- 只要有一个失败了就 直接失败 

### Promise.race([p1,p2,p3]) 方法

`(promises) => {}` 

(1) promises: 包含 n 个 promise 的数组 

说明: 返回一个新的 promise, 

- 第一个完成的 promise 的结果状态就是最终的结果状态

## 关键问题

### 如何改变Promise对象状态

1. resolve() 变fulfilled
2. reject() 变rejected
3. throw 抛出问题 变rejected

### 为promise指定多个回调函数, 都会调用吗

当 promise 改变为对应状态时都会调用 

### 改变 promise 状态和指定回调函数谁先谁后

(1) 都有可能, , 但也可以先改状态再指定回调

- 正常情况（**同步**执行）下是先改状态再指定回调
  - 在执行器中直接调用 resolve()/reject() 
  - 延迟更长时间才调用 then() 
- 如果**异步**情况下指定回调，那么就可以先指定回调再改状态，实际情况下，异步任务居多

(2) 什么时候才能得到数据? 即回调函数什么时候执行

- 如果先指定的**回调**, 那当状态发生改变时, 回调函数就会调用, 得到数据 

- 如果先改变的**状态**, 那当指定回调时, 回调函数就会调用, 得到数据 

### promise.then()返回的新 promise 的结果状态由什么决定

(1) 简单表达: 由 then()指定的**回调函数的返回值**决定 

(2) 详细表达: 

-  如果抛出**异常**, 新 promise 变为 rejected, reason 为抛出的异常 
- 如果返回的是**非 promise** 的任意值, 新 promise 变为 resolved, value 为返回的值 
- 如果返回的是另一个新 **promise**, 此 promise 的结果就会成为新 promise 的结果 

### promise 如何串连多个操作任务

(1) promise 的 then()返回一个新的 promise, 可以开成 then()的链式调用 

(2) 通过 then 的链式调用串连多个同步/异步任务

### promise 异常穿透

(1) 当使用 promise 的 then 链式调用时, 可以**在最后指定失败的回调**,  `.catch(reason=>{...})`

(2) 前面任何操作出了异常, 都会传到最后失败的回调中处理 

### 中断 promise 链

(1) 当使用 promise 的 then 链式调用时, 在中间中断, 不再调用后面的回调函数 

(2) 唯一方法: 在回调函数中**返回一个 pendding 状态**的 promise 对象

`return new Promise(()=>{})`

# 手写Promise

依次实现

- 构造函数：输入参数为执行器函数executor
- 实例属性：promiseState，promiseResult
- 改变Promise对象的3种方法
  - 构造函数方法：resolve()，reject()
  - throw抛出异常，try catch接收异常
- 原型方法：then() 指定回调函数
- 考虑先指定回调函数，再改变Promise对象状态
- 考虑指定多个回调函数，但不互相覆盖
- 考虑then() 的返回结果是一个Promise对象
- 考虑异步情况下then() 的返回结果
- 考虑代码复用，将then() 封装优化
- 原型方法：catch() 考虑异常穿透和值传递，添加回调默认值
- 构造函数方法：resolve()
- 构造函数方法：reject()
- 构造函数方法：all()
- 构造函数方法：race ()
- 考虑then()方法回调异步执行：用setTimeout包起来
- ES6 Class实现

# ==async 与 await==

mdn 文档 https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Statements/async_function https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Operators/await 

## async 函数 

在函数声明前面加async，它就变成async函数，函数自动**返回Promise对象**

1. 函数的返回值为 promise 对象 
1. promise 对象的结果由 async 函数执行的返回值决定 （**和then的返回规则**一样）
   - 非Promise：返回成功Promise；是Promise，返回本身

## await 表达式 

`await`一般放在一个Promise对象前面，用来获取它**成功**的值，失败的值用`try catch`获取

``` js
try{
    let res2=await p2
} catch(e){
    console.log(e);
}
```

1. await 右侧的表达式一般为 promise 对象, 但也可以是其它的值 
1. 如果表达式是 promise 对象, await 返回的是 **promise 成功的值** 
1. 如果表达式是其它值, 直接将此值作为 await 的返回值

注意 

1. await 必须**写在 async 函数中**, 但 async 函数中可以没有 await 
2. 如果 await 的 promise 失败了, 就会抛出异常, 需要通过 try...catch 捕获处理

# ==其他实例==

**fs读文件相关**：

- 用Promise和then让读文件操作按顺序进行：[代码](..\Promise基础\2-fs模块.js)

- 把fs封装成返回Promise对象的函数：[代码](..\Promise基础\4-封装读取文件函数.js)

- 用util.promisify()把fs变成它的Promise版本：[代码](..\Promise基础\5-utils.promisefy方法.js)

  - 这个方法适用于一些函数，这种函数需要有回调函数作为参数来进行错误处理，比如说fs.readFile，用这个方法可以让函数执行和原来一样的功能，只是返回类型变成Promise

  - ```js
    util=require('util')
    let myReadFile= util.promisify(fs.readFile)
    ```

- 用async await让读文件操作按顺序进行：[代码](..\Async和Await\3-async+await+fs.js)

**AJAX相关**：

- 用Promise和then指定AJAX事件处理程序的操作：[代码](..\Promise基础\3-AJAX请求.html)
- 把AJAX封装成返回Promise对象的函数：[代码](..\Promise基础\6-封装AJAX请求函数.html)
- 用async await获取AJAX成功响应的响应体：[代码](..\Async和Await\4-async+await+AJAX.html)

# 附加知识

thenable

https://blog.csdn.net/weixin_42309926/article/details/108525111

可能接收到的Promise并不是原生Promise

找类Promise的对象：判断有没有then方法，即thenable

``` js
if(p!==null&&(typeof p==="object"||typeof p==="function")&&(typeof p.then==="function")){
    console.log("这是一个thenable")
}else{
    console.log("这不是一个thenable")
}
```
